openapi: 3.0.1
info:
  title: Adzerk Management API - Advertisers
  description: Advertiser related Adzerk Management API
  version: '1.0'
servers:
  - url: 'https://api.adzerk.net'
tags:
  - name: advertisers
    description: Manage Advertisers
paths:
  /v1/advertiser:
    post:
      tags:
        - advertisers
      description: Create Advertiser
      operationId: createAdvertiser
      security:
        - ApiKeyAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - Title
                - IsActive
              properties:
                Title:
                  type: string
                IsActive:
                  type: boolean
                  default: false
                PlacementLimit:
                  type: integer
                  format: int32
                  nullable: true
                FreqCap:
                  type: integer
                  format: int32
                  nullable: true
                FreqCapDuration:
                  type: integer
                  format: int32
                  nullable: true
                FreqCapType:
                  type: integer
                  format: int32
                  nullable: true
                CapType:
                  type: integer
                  format: int32
                  default: 4
                  nullable: true
                DailyCapAmount:
                  type: integer
                  format: int32
                  nullable: true
                LifetimeCapAmount:
                  type: integer
                  format: int32
                  nullable: true
                IsDeleted:
                  type: boolean
                  default: false
      responses:
        200:
          description: Advertiser Created
          content:
            application/json:
              schema:
                $ref: './schemas/advertiser.yaml#/schemas/Advertiser'
components:
  securitySchemes:
    $ref: './components/security-schemes.yaml#/components/securitySchemes'