openapi: 3.0.1
info:
  title: Adzerk Management API - Entity Counts
  description: Entity Counts related Adzerk Management API
  version: '1.0'
servers:
  - url: 'https://api.adzerk.net'
tags:
  - name: entity-counts
    description: Entity Counts
paths:
  /v1/asset:
    get:
      tags:
        - assets
      description: list Assets
      operationId: listAssets
      security:
        - ApiKeyAuth: []
      parameters:
        - name: pageSize
          in: query
          description: The size of the page to be returned
          required: false
          schema:
            type: integer
            format: int32
            nullable: true
        - name: page
          in: query
          description: The page number to be returned
          required: false
          schema:
            type: integer
            format: int32
            nullable: true
      responses:
        200:
          description: Paged list of Assets
          content:
            application/json:
              schema:
                $ref: './schemas/asset.yaml#/schemas/AssetList'
  '/v1/asset/{assetId}':
    parameters:
      - name: assetId
        in: path
        description: Id of the Asset
        required: true
        schema:
          type: integer
          format: int32
    get:
      tags:
        - assets
      description: Get an existing Asset
      operationId: getAsset
      security:
        - ApiKeyAuth: []
      responses:
        200:
          description: The existing Asset
          content:
            application/json:
              schema:
                $ref: './schemas/asset.yaml#/schemas/AssetDetails'
  '/v1/advertiser/{advertiserId}/asset':
    parameters:
      - name: advertiserId
        in: path
        description: Id of the Advertiser
        required: true
        schema:
          type: integer
          format: int32
    get:
      tags:
        - assets
      description: List Assets for Advertiser
      operationId: listAdvertiserAssets
      security:
        - ApiKeyAuth: []
      parameters:
        - name: pageSize
          in: query
          description: The size of the page to be returned
          required: false
          schema:
            type: integer
            format: int32
            nullable: true
        - name: page
          in: query
          description: The page number to be returned
          required: false
          schema:
            type: integer
            format: int32
            nullable: true
      responses:
        200:
          description: Paged list of Assets for Advertiser
          content:
            application/json:
              schema:
                $ref: './schemas/asset.yaml#/schemas/AssetList'
    post:
      tags:
        - assets
      description: Create Asset
      operationId: createAsset
      security:
        - ApiKeyAuth: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: './schemas/asset.yaml#/schemas/AssetInput'
      responses:
        200:
          description: Asset Created
          content:
            application/json:
              schema:
                $ref: './schemas/asset.yaml#/schemas/Asset'
  '/v1/asset/{assetId}/delete':
    parameters:
      - name: assetId
        in: path
        description: Id of the Asset
        required: true
        schema:
          type: integer
          format: int32
    post:
      tags:
        - assets
      description: Delete an existing Asset
      operationId: deleteAsset
      security:
        - ApiKeyAuth: []
      responses:
        200:
          description: Successfully Deleted
  '/v1/asset/{assetId}/upload':
    parameters:
      - name: assetId
        in: path
        description: Id of the Asset
        required: true
        schema:
          type: integer
          format: int32
    post:
      tags:
        - assets
      description: Upload content to an existing Asset
      operationId: uploadAssetContent
      security:
        - ApiKeyAuth: []
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                  description: This must be an image file
      responses:
        200:
          description: Successfully Uploaded

components:
  securitySchemes:
    $ref: './components/security-schemes.yaml#/components/securitySchemes'
