AWSTemplateFormatVersion: '2010-09-09'
Description: S3 Hosting Bucket for the Management API Specification
Resources:
  ManagementApiSpecHostingBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      AccessControl: PublicRead
      BucketName: developer-exp-management-api-specification
      WebsiteConfiguration:
        IndexDocument: openapi-3.yaml
Outputs:
  WebsiteURL:
    Value:
      'Fn::GetAtt':
        - ManagementApiSpecHostingBucket
        - WebsiteURL
    Description: URL for website hosted on S3