openapi: 3.0.1
info:
  title: Adzerk Management API - Creative Templates
  description: Creative Template related Adzerk Management API
  version: '1.0'
servers:
  - url: 'https://api.adzerk.net'
tags:
  - name: creative-template
    description: Manage Creative Templates
paths:
  '/v2/creative-templates':
    post:
      tags:
        - creative-template
      description: Create new Creative Template
      operationId: create
      security:
        - ApiKeyAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - Name
                - Description
              properties:
                Name:
                  type: string
                  minLength: 1
                  maxLength: 50
                Description:
                  type: string
                  minLength: 1
                  maxLength: 100
                IsArchived:
                  type: boolean
                  default: false
                Fields:
                  type: array
                  items:
                    type: object
                    required:
                      - Name
                      - Variable
                    properties:
                      Name:
                        type: string
                        maxLength: 255
                      Variable:
                        type: string
                        pattern: '^ct[a-zA-Z0-9]+'
                      Type:
                        type: string
                        enum: [String, File, ExternalFile, Array]
                      Required:
                        type: boolean
                        default: false
                      Description:
                        type: string
                      Hidden:
                        type: boolean
                        default: false
                      Default:
                        type: object
      responses:
        200:
          description: The newly created Creative Template
          content:
            application/json:
              schema:
                $ref: './schemas/creative-template.yaml#/schemas/CreativeTemplate'
components:
  securitySchemes:
    $ref: './components/security-schemes.yaml#/components/securitySchemes'