openapi: 3.0.1
info:
  title: Adzerk Management API - Creatives
  description: Creatives related Adzerk Management API
  version: '1.0'
servers:
  - url: 'https://api.adzerk.net'
tags:
  - name: creative
    description: Manage Creatives
paths:
  /v1/creative:
    post:
      tags:
        - creative
      description: Create Creative
      operationId: create
      security:
        - ApiKeyAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - AdvertiserId
                - AdTypeId
                - IsActive
              properties:
                AdvertiserId:
                  type: integer
                  format: int32
                AdTypeId:
                  type: integer
                  format: int32
                IsActive:
                  type: boolean
                  default: false
                Title:
                  type: string
                  nullable: true
                ImageName:
                  type: string
                  nullable: true
                Body:
                  type: string
                  nullable: true
                Url:
                  type: string
                  nullable: true
                  format: url
                Alt:
                  type: string
                  nullable: true
                IsDeleted:
                  type: boolean
                  nullable: true
                IsHTMLJS:
                  type: boolean
                  nullable: true
                ScriptBody:
                  type: string
                  nullable: true
                Metadata:
                  type: string
                  nullable: true
                ImageLink:
                  type: string
                  nullable: true
                SaveEmptyCreative:
                  type: boolean
                  nullable: true
                IsNoTrack:
                  type: boolean
                  nullable: true
                IsNetworkAd:
                  type: boolean
                  nullable: true
                TemplateId:
                  type: integer
                  format: int32
                  nullable: true
                TemplateValues:
                  type: string
                  nullable: true
      responses:
        200:
          description: Creative Created
          content:
            application/json:
              schema:
                $ref: './schemas/creative.yaml#/schemas/Creative'
  '/v1/creative/{id}':
    parameters:
      - name: id
        in: path
        description: The Id of the Creative to update
        required: true
        schema:
          type: integer
          format: int32
    put:
      tags:
        - creative
      description: Update Creative
      operationId: update
      security:
        - ApiKeyAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - Id
                - AdvertiserId
                - AdTypeId
                - IsActive
              properties:
                Id:
                  type: integer
                  format: int32
                AdvertiserId:
                  type: integer
                  format: int32
                AdTypeId:
                  type: integer
                  format: int32
                IsActive:
                  type: boolean
                  default: false
                Title:
                  type: string
                  nullable: true
                ImageName:
                  type: string
                  nullable: true
                Body:
                  type: string
                  nullable: true
                Url:
                  type: string
                  nullable: true
                  format: url
                Alt:
                  type: string
                  nullable: true
                IsDeleted:
                  type: boolean
                  nullable: true
                IsHTMLJS:
                  type: boolean
                  nullable: true
                ScriptBody:
                  type: string
                  nullable: true
                Metadata:
                  type: string
                  nullable: true
                ImageLink:
                  type: string
                  nullable: true
                SaveEmptyCreative:
                  type: boolean
                  nullable: true
                IsNoTrack:
                  type: boolean
                  nullable: true
                IsNetworkAd:
                  type: boolean
                  nullable: true
                TemplateId:
                  type: integer
                  format: int32
                  nullable: true
                TemplateValues:
                  type: string
                  nullable: true
      responses:
        200:
          description: Creative Updated
          content:
            application/json:
              schema:
                $ref: './schemas/creative.yaml#/schemas/Creative'
    get:
      tags:
        - creative
      description: Get Creative
      operationId: get
      security:
        - ApiKeyAuth: []
      responses:
        200:
          description: The requested Creative
          content:
            application/json:
              schema:
                $ref: './schemas/creative.yaml#/schemas/Creative'
  '/v1/creative/{id}/upload':
    post:
      tags:
        - creative
      description: Upload Creative Image
      operationId: uploadImage
      security:
        - ApiKeyAuth: []
      parameters:
        - name: id
          in: path
          description: The Id of the Creative to upload an image for
          required: true
          schema:
            type: integer
            format: int32
        - name: sizeOverride
          in: query
          description: Add this to upload an image that is a different dimension than the creative's `adTypeId`
          schema:
            type: boolean
        - name: fieldName
          in: query
          description: Specifies which image field (of Type `File`) the file will be uploaded to. Can be used with single-image and multiple-image templates. If a template has only one image, `fieldName` is not required.
          schema:
            type: string
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                image:
                  type: string
                  format: binary
      responses:
        200:
          description: Creative Updated
          content:
            application/json:
              schema:
                $ref: './schemas/creative.yaml#/schemas/Creative'

  '/v1/advertiser/{id}/creatives':
    get:
      tags:
        - creative
      description: List Creatives for Advertiser
      operationId: listForAdvertiser
      security:
        - ApiKeyAuth: []
      parameters:
        - name: id
          in: path
          description: Advertiser Id to list Creatives for
          required: true
          schema:
            type: integer
            format: int32
        - name: pageSize
          in: query
          description: The size of the page to be returned
          required: false
          schema:
            type: integer
            format: int32
            nullable: true
        - name: page
          in: query
          description: The page number to be returned
          required: false
          schema:
            type: integer
            format: int32
            nullable: true
      responses:
        200:
          description: Paged list of Creatives for the Advertiser
          content:
            application/json:
              schema:
                $ref: './schemas/creative.yaml#/schemas/CreativeList'
components:
  securitySchemes:
    $ref: './components/security-schemes.yaml#/components/securitySchemes'