openapi: 3.0.1
info:
  title: Adzerk Management API - Geotargeting
  description: Advertiser related Adzerk Management API
  version: '1.0'
servers:
  - url: 'https://api.adzerk.net'
tags:
  - name: geo-target
    description: Manage Geotargeting
paths:
  '/v1/flight/{flightId}/geotargeting':
    post:
      tags:
        - geo-targeting
      operationId: create
      security:
        - ApiKeyAuth: []
      parameters:
        - name: flightId
          description: The Flight Id to update the Site Zone Targeting for
          in: path
          required: true
          schema:
            type: integer
            format: int32
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                CountryCode:
                  type: string
                Region:
                  type: string
                MetroCode:
                  type: string
                IsExclude:
                  type: boolean
                  nullable: true
      responses:
        200:
          description: The newly created Geo Target
          content:
            application/json:
              schema:
                $ref: './schemas/geo-target.yaml#/schemas/GeoTarget'
  '/v1/flight/{flightId}/geotargeting/{locationId}':
    parameters:
      - name: flightId
        description: The Flight Id to update the Site Zone Targeting for
        in: path
        required: true
        schema:
          type: integer
          format: int32
      - name: locationId
        description: The Id of the Site Zone Targeting to update
        in: path
        required: true
        schema:
          type: integer
          format: int32
    put:
      tags:
        - geo-targeting
      operationId: update
      security:
        - ApiKeyAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                CountryCode:
                  type: string
                Region:
                  type: string
                MetroCode:
                  type: string
                IsExclude:
                  type: boolean
                  nullable: true
      responses:
        200:
          description: The updated Geo Target
          content:
            application/json:
              schema:
                $ref: './schemas/geo-target.yaml#/schemas/GeoTarget'
    get:
      tags:
        - geo-targeting
      operationId: get
      security:
        - ApiKeyAuth: []
      responses:
        200:
          description: The Geo Target
          content:
            application/json:
              schema:
                $ref: './schemas/geo-target.yaml#/schemas/GeoTarget'
  '/v1/flight/{flightId}/geotargeting/{locationId}/delete':
    get:
      tags:
        - geo-targeting
      operationId: delete
      security:
        - ApiKeyAuth: []
      parameters:
        - name: flightId
          description: The Flight Id to update the Site Zone Targeting for
          in: path
          required: true
          schema:
            type: integer
            format: int32
        - name: locationId
          description: The Id of the Site Zone Targeting to update
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        200:
          description: Successfully Deleted
  /v1/countries:
    get:
      tags:
        - geo-targeting
      operationId: listCountries
      security:
        - ApiKeyAuth: []
      responses:
        200:
          description: A list of countries
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: './schemas/geo-target.yaml#/schemas/Country'
  '/v1/country/{countryCode}/regions?version=2':
    get:
      tags:
        - geo-targeting
      operationId: listRegionsForCountry
      security:
        - ApiKeyAuth: []
      parameters:
        - name: countryCode
          description: The Country Code to list Regions for
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: A country with Regions included
          content:
            application/json:
              schema:
                $ref: './schemas/geo-target.yaml#/schemas/Country'
  '/v1/region/{regionCode}':
    get:
      tags:
        - geo-targeting
      operationId: listMetroCodesForRegion
      security:
        - ApiKeyAuth: []
      parameters:
        - name: regionCode
          description: The Region Code to get Metros for
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: A list of Metros
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: './schemas/geo-target.yaml#/schemas/Metro'
components:
  securitySchemes:
    $ref: './components/security-schemes.yaml#/components/securitySchemes'