schemas:

  Site:
    type: object
    properties:
      Id:
        type: integer
        format: int32
        nullable: true
      Title:
        type: string
      Url:
        type: string
      NetworkMargin:
        type: number
        format: float
        nullable: true
      CustomRelevancyScore:
        type: integer
        format: int32
        minimum: 1
        maximum: 1000
        nullable: true
      IsDeleted:
        type: boolean
        nullable: true
      PublisherAccountId:
        type: integer
        format: int32
        nullable: true
        deprecated: true

  SiteList:
    type: object
    properties:
      page:
        type: integer
        format: int32
      pageSize:
        type: integer
        format: int32
      totalPages:
        type: integer
        format: int32
      totalItems:
        type: integer
        format: int64
      items:
        type: array
        items:
          $ref: '#/schemas/Site'