openapi: 3.0.1
info:
  title: Adzerk Decision API
  description: Adzerk Decision API
  version: '1.0'
servers:
  - url: '{protocol}://e-{networkId}.adzerk.net'
    variables:
      protocol:
        enum:
          - http
          - https
        default: https
      networkId:
        description: Your Adzerk Network Id
        default: '23'
tags:
  - name: decision
    description: Adzerk Decision API Endpoint
  - name: userdb
    description: Adzerk UserDB
paths:
  /api/v2:
    post:
      tags:
        - decision
      description: Request Decision(s)
      operationId: getDecisions
      requestBody:
        content:
          application/json:
            schema:
              type: object
            examples:
              '0':
                value: >-
                  {"placements": [{ "divName": "header", "networkId": 23, "siteId": 667480, "adTypes": [5] }] }
              '1':
                value: >-
                  {"placements": [{ "divName": "header", "networkId": 23, "siteId": 667480, "adTypes": [5] }], "user": { "key": "ABC123" } }
              '2':
                value: >-
                  {"placements": [{ "divName": "header", "networkId": 23, "siteId": 667480, "adTypes": [5], "count": 5 }], "user": { "key": "ABC123" } }
              '3':
                value: >-
                  {"placements": [{ "divName": "header", "networkId": 23, "siteId": 667480, "adTypes": [5], "count": 5 }], "user": { "key": "ABC123" }, "includePricingData": true }
              '4':
                value: >-
                  {"placements": [{ "divName": "header", "networkId": 23, "siteId": 667480, "adTypes": [5], "eventIds": [1, 2], "count": 5}], "user": { "key": "ABC123" }, "includePricingData": true }
      responses:
        '400':
          description: Bad Request
        '200':
          description: Successful decision request
          content:
            application/json:
              schema:
                '$ref': '#/components/schemas/Response'
  '/udb/{networkId}/set/i.gif':
    get:
      tags:
        - userdb
      description: Set User Cookie
      operationId: setUserCookie
      parameters:
        - name: networkId
          in: path
          description: Your Network Id
          required: true
          schema:
            type: integer
            format: int32
        - name: userKey
          in: query
          description: UserDB Id for the user
          required: true
          schema:
            type: string
      responses:
        200:
          description: Success
  '/udb/{networkId}/custom':
    post:
      tags:
        - userdb
      description: Add Custom Properties to a User
      operationId: addCustomProperties
      security:
        - ApiKeyAuth: []
      parameters:
        - name: networkId
          in: path
          description: Your Network Id
          required: true
          schema:
            type: integer
            format: int32
        - name: userKey
          in: query
          description: The User's UserDB Key
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
      responses:
        200:
          description: Success
  '/udb/{networkId}/interest/i.gif':
    get:
      tags:
        - userdb
      description: Add Interests to a User
      operationId: addInterests
      parameters:
        - name: networkId
          in: path
          description: Your Network Id
          required: true
          schema:
            type: integer
            format: int32
        - name: userKey
          in: query
          description: The User's UserDB Key
          required: true
          schema:
            type: string
        - name: interest
          in: query
          description: Comma Seperated list of interests
          required: true
          schema:
            type: string
      responses:
        200:
          description: Success
  '/udb/{networkId}/rt/{advertiserId}/{retargetingSegmentId}/i.gif':
    get:
      tags:
        - userdb
      description: Add User to a Retargeting Segment
      operationId: addRetargetingSegment
      parameters:
        - name: networkId
          in: path
          description: Your Network Id
          required: true
          schema:
            type: integer
            format: int32
        - name: advertiserId
          in: path
          description: The Advertiser's ID
          required: true
          schema:
            type: integer
            format: int32
        - name: retargetingSegmentId
          in: path
          description: The Segment's ID
          required: true
          schema:
            type: integer
            format: int32
        - name: userKey
          in: query
          description: The User's UserDB Key
          required: true
          schema:
            type: string
      responses:
        200:
          description: Success
  '/udb/{networkId}/optout/i.gif':
    get:
      tags:
        - userdb
      description: Opt-Out a User
      operationId: optOut
      parameters:
        - name: networkId
          in: path
          description: Your Network Id
          required: true
          schema:
            type: integer
            format: int32
        - name: userKey
          in: query
          description: The User's UserDB Key
          required: true
          schema:
            type: string
      responses:
        200:
          description: Sucess
  '/udb/{networkId}/read':
    get:
      tags:
        - userdb
      description: Read a User's UserDB Record
      operationId: read
      parameters:
        - name: networkId
          in: path
          description: Your Network Id
          required: true
          schema:
            type: integer
            format: int32
        - name: userKey
          in: query
          description: The User's UserDB Key
          required: true
          schema:
            type: string
      responses:
        200:
          description: The UserDB record
          content:
            application/json:
              schema:
                type: object
  '/udb/{networkId}':
    delete:
      tags:
        - userdb
      description: Forget User
      operationId: forget
      security:
        - ApiKeyAuth: []
      parameters:
        - name: networkId
          in: path
          description: Your Network Id
          required: true
          schema:
            type: integer
            format: int32
        - name: userKey
          in: query
          description: The User's UserDB Key
          required: true
          schema:
            type: string
      responses:
        200:
          description: Success
  '/udb/{networkId}/consent':
    post:
      tags:
        - userdb
      description: GDPR Consent
      operationId: gdprConsent
      security:
        - ApiKeyAuth: []
      parameters:
        - name: networkId
          in: path
          description: Your Network Id
          required: true
          schema:
            type: integer
            format: int32
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GdprConsent'
      responses:
        200:
          description: Success
  '/udb/{networkId}/sync/i.gif':
    get:
      tags:
        - userdb
      description: User Matching
      operationId: matchUser
      parameters:
        - name: networkId
          in: path
          description: Your Network Id
          required: true
          schema:
            type: integer
            format: int32
        - name: userKey
          in: query
          description: The User's UserDB Key
          required: true
          schema:
            type: string
        - name: partnerId
          in: query
          description: The ID of the RTB provider in Adzerk. Contact Support if you don't have the ID.
          required: true
          schema:
            type: integer
            format: int32
        - name: userId
          in: query
          description: This is the UserID the individual RTB provider has of the user. This is NOT the UserDB userkey.
          required: true
          schema:
            type: integer
            format: int32
      responses:
        200:
          description: Success
components:
  schemas:
    Request:
      type: object
      properties:
        placements:
          description: One or more Placement objects
          type: array
          items:
            $ref: '#/components/schemas/Placement'
        user:
          $ref: '#/components/schemas/User'
          nullable: true
        keywords:
          description: 'Keywords for keyword Targeting. Such as `"keywords": ["foo", "bar", "baz"]`.'
          type: array
          nullable: true
          items:
            type: string
        url:
          description: The current page URL
          type: string
          nullable: true
        referrer:
          description: The referrer URL
          type: string
          nullable: true
        ip:
          description: The IP address. Required for [Geo-Targeting](https://dev.adzerk.com/docs/geo-location)
          type: string
          nullable: true
        blockedCreatives:
          description: Numeric creative ids to disregard for ad selection
          type: array
          nullable: true
          items:
            type: integer
        isMobile:
          description: If true, only ads containing a single image will be returned
          type: boolean
          nullable: true
        includePricingData:
          description: If true, return pricing data for the decision in the response
          type: boolean
          nullable: true
        notrack:
          description: If true, only return ads that are set to honor Do Not Track
          type: boolean
          nullable: true
        enableBotFiltering:
          description: If making a client-side request, set to true. Defaults to false to ensure a server isn't seen as a bot. See [here](https://dev.adzerk.com/docs/tracking-overview#section-bot-filtering) for more info
          type: boolean
          nullable: true
        enableUserDBIP:
          description: If true, override the IP address of the request with the IP address supplied on the UserKey. If no IP address is found on the UserKey, this will fall back to the IP address on the request. Requires UserDB
          nullable: true
          type: boolean
        consent:
          description: Object that sets the data consent preferences. Other consent settings are available in the GDPR settings documentation.
          type: object
          nullable: true
          properties:
            gdpr:
              type: boolean
        deviceID:
          description: RTB requests only - sets an Identifier for Advertisers (IFA or IDFA)
          type: string
          nullable: true
      required:
        - placements
    Placement:
      type: object
      properties:
        divName:
          description: A unique name for the placement defined by you
          type: string
        networkId:
          description: The numeric network id
          type: integer
          format: int32
        siteId:
          description: The numeric site id
          type: integer
          format: int32
        adTypes:
          description: One or more integer ad types. More info [here](https://dev.adzerk.com/docs/ad-sizes)
          type: array
          items:
            type: integer
        zoneIds:
          description: Zone IDs to use
          type: array
          nullable: true
          items:
            type: integer
        campaignId:
          description: A numeric campaign id; if specified, only consider ads in that campaign
          type: integer
          format: int32
          nullable: true
        flightId:
          description: A numeric ad (flight-creative map) id; if specified, only serve that ad if possible
          type: integer
          format: int32
          nullable: true
        adId:
          description: A numeric ad (flight-creative map) id; if specified, only serve that ad if possible
          type: integer
          format: int32
          nullable: true
        clickUrl:
          description: The ad's click-through URL
          type: string
          nullable: true
        properties:
          description: A map of key/value pairs used for [Custom Targeting](https://dev.adzerk.com/docs/custom-targeting)
          type: object
          nullable: true
        eventIds:
          description: An array of numeric event types. Requests tracking URLs for custom events. See here for [Event Tracking IDs](https://dev.adzerk.com/v1.0/docs/custom-event-tracking)
          type: array
          nullable: true
          items:
            type: integer
        overrides:
          description: An object that overrides values for an advertiser, campaign, flight or ad. Used especially for header bidding
          type: object
          nullable: true
        contentKeys:
          description: 'A map of key/value pairs used with [ContentDB](https://dev.adzerk.com/docs/contentdb-1). The format is `"contentKeys": {"schema": "contentKey"}`'
          type: object
          nullable: true
          additionalProperties:
            type: integer
        count:
          description: (BETA) The number of ads to return per placement. Integer between 1 and 20
          type: integer
          format: int32
          nullable: true
        proportionality:
          description: (BETA) If true, fills ads in a multi-winner placement in proportion to the flight's goals
          type: boolean
          nullable: true
        ecpmPartition:
          description: (BETA) The name of the eCPM Partition that should be used to source eCPM data for auctions
          type: string
          nullable: true
    User:
      description: Object containing the UserKey used for [UserDB targeting](https://dev.adzerk.com/docs/userdb-1)
      type: object
      properties:
        key:
          description: The UserKey used for UserDB Targeting
          type: string
    Decision:
      type: object
      properties:
        adId:
          type: integer
        creativeId:
          type: integer
        flightId:
          type: integer
        campaignId:
          type: integer
        priorityId:
          type: integer
        clickUrl:
          type: string
          format: uri
        contents:
          type: array
          items:
            $ref: '#/components/schemas/Content'
        impressionUrl:
          type: string
          format: uri
        events:
          type: array
          items:
            $ref: '#/components/schemas/Event'
        pricing:
          $ref: '#/components/schemas/PricingData'
    Event:
      type: object
      properties:
        id:
          type: integer
          format: int32
        url:
          type: string
          format: uri
    Content:
      type: object
      properties:
        type:
          type: string
        template:
          type: string
        customTemplate:
          type: string
        data:
          $ref: '#/components/schemas/DecisionData'
        body:
          type: string
    DecisionData:
      type: object
      properties:
        imageURL:
          type: string
          format: uri
        title:
          type: string
        width:
          type: integer
          format: int32
        height:
          type: integer
          format: int32
        customData:
          type: object
    PricingData:
      type: object
      properties:
        price:
          type: number
          format: float
        clearPrice:
          type: number
          format: float
        revenue:
          type: number
          format: float
        rateType:
          type: integer
        eCPM:
          type: number
          format: float
    Response:
      type: object
      properties:
        user:
          $ref: '#/components/schemas/User'
        decisions:
          type: object
        explain:
          type: object
    GdprConsent:
      type: object
      properties:
        userKey:
          type: string
        consent:
          $ref: '#/components/schemas/Consent'
    Consent:
      type: object
      properties:
        gdpr:
          type: boolean
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-Adzerk-ApiKey