name: Publish Decision Spec Packages

on:
  release:
    types: [published]

env:
  WORKINGDIRECTORY_DECISION: build/ts/decision

jobs:
  typescript:
    name: Publish Typescript Package
    runs-on: ubuntu-latest
    steps:
      - id: a9c19221-2149-41f2-91d7-e8411bf3ecc5
        name: Checkout Repository
        uses: actions/checkout@v3
      
      - id: ba48f425-ccc1-4288-8ff6-4a1812e83224
        name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      
      - id: e75378b3-35d5-4f84-a871-d47e518f2d04
        name: Install Dependencies
        run: npm clean-install

      - id: ced9f2a9-8b4a-4082-a0d1-7791c847d632
        name: Build Typescript Components from Decision Spec
        run: npm run build-decision-typescript

      - id: db6068b8-f5ed-4968-847e-b642595243fd
        name: Install Typescript Compiler Globally
        run: npm install --global typescript

      - id: e842d27d-141c-47f2-b64c-2c5702984edf
        name: Compile Package
        working-directory: ${WORKINGDIRECTORY_DECISION}
        run: tsc --outDir dist --declaration *.ts

      - id: db7f8f85-c695-48a1-acfc-a2898987dfa3
        name: Create package.json File
        run: cp decision/package-config/npm/* ${WORKINGDIRECTORY_DECISION}

      - id: c8734e87-1bb8-4340-9ab2-fd5cabb1ac6b
        name: Update Version package.json to Released Version
        working-directory: ${WORKINGDIRECTORY_DECISION}
        run: npm pkg set "version"="${GITHUB_REF_NAME}"

      - id: b5abe142-c11f-4951-8809-4bc118b4027d
        name: Publish NPM Package
        working-directory: ${WORKINGDIRECTORY_DECISION}
        run: |
          echo "Publishing tag ${GITHUB_REF_NAME}."
          npm publish --dry-run
